### ISSUE TITLE
Define a `PhysicalFunction` with another one

### ISSUE THREAD

**Issue by bmxam** [bcube-project/Bcube.jl#20]
We cannot use a `PhysicalFunction` in the definition of another one. The following MWE raises an error:
```julia
using Bcube
mesh = one_cell_mesh(:line)

ρ = PhysicalFunction(x -> 1.0)
ρu = PhysicalFunction(x -> ρ(x) * 2)

dΩ = Measure(CellDomain(mesh), 1)
@show Bcube.compute(∫(ρu)dΩ)
```

Of course to overcome this we can use an intermediate variable
```julia
_ρ(x) = 1
ρ = PhysicalFunction(x -> _ρ(x))
ρu = PhysicalFunction(x -> _ρ(x) * 2)
```

**Comment by ghislainb** [comment]
- Actually I think it's not a bug and this is rather the expected behavior.

`CellFunction` can be evaluated at a `CellPoint` or a `FacePoint` because `DomainStyle` is defined for those points. 
Here in:
```julia
PhysicalFunction(x -> ρ(x) * 2)
```
`x` is a `SVector` of coordinates for which `DomainStyle` is not defined, so evaluation of `ρ(x)` is not possible in the inner scope.

We can add a new feature to do so if we assume that `x` has the same `DomainStyle` as the `CellFunction` by default, but it will remove the "safety barriers" in a sense (and it could even be wrong if you compose `ReferenceFunction` with `PhysicalFunction`)


- As `CellFunction` are `AbstractLazy`, you can also simply do:

```julia
ρ = PhysicalFunction(x -> 1.0)
ρu = 2 * ρ
```

**Comment by bmxam** [comment]
I agree, the solution is simply what you suggested:
```julia
ρ = PhysicalFunction(x -> 1.0)
ρu = 2 * ρ
```
So no need to change anything.
