### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by ghislainb** [bcube-project/Bcube.jl#77]
@JuliaRegistrator register

**Comment by ghislainb** [comment]
@JuliaRegistrator register

**Comment by bmxam** [comment]
@JuliaRegistrator register

**Comment by bmxam** [comment]
@JuliaRegistrator register

**Comment by bmxam** [comment]
@JuliaRegistrator register

**Comment by ghislainb** [comment]
@JuliaRegistrator register

**Comment by ghislainb** [comment]
@JuliaRegistrator register

**Comment by bmxam** [comment]
@JuliaRegistrator register

**Comment by bmxam** [comment]
@JuliaRegistrator register

**Comment by bmxam** [comment]
@JuliaRegistrator register

**Comment by bmxam** [comment]
@JuliaRegistrator register

**Comment by bmxam** [comment]
@JuliaRegistrator register

**Comment by bmxam** [comment]
@JuliaRegistrator register

**Comment by bmxam** [comment]
@JuliaRegistrator register

**Comment by bmxam** [comment]
@JuliaRegistrator register

**Comment by bmxam** [comment]
@JuliaRegistrator register

Release notes:

This release is breaking.

## Breaking changes

- the `struct` `AffineFESystem` now takes a `linsolve!` kwarg. This kwarg should be a `Function`` of the form `f(y, A, x)` where `A` is the bilinear form matrix, `x` the right hand side, and `y` a preallocated output vector in which the result should be stored. The default solver is `(y, A, x) -> y .= A \\ x`.
- the `solve(system::AffineFESystem, t::Number = 0.0)` function drops the `alg` kwarg
- the dirichlet conditions must now be set with  a function `t -> AbstractLazy` rather than a function of `(time, x)`. Hence, the dirichlet conditions dict must will look like this `Dict(String => t -> AbstractLazy)`. For instance, `Dict("xmin" => 0., "xmax" => t -> PhysicalFunction(x -> 3*t*norm(x), "ymin" => FEFunction(U_scalar))

**Comment by bmxam** [comment]
@JuliaRegistrator register

**Comment by bmxam** [comment]
@JuliaRegistrator register

**Comment by bmxam** [comment]
@JuliaRegistrator register
